// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5EOIjwN8MEOFoACZRAxYOjwTyl75dceg',
    appId: '1:816152989290:web:2c729d94223d594720c413',
    messagingSenderId: '816152989290',
    projectId: 'easyway-cms',
    authDomain: 'easyway-cms.firebaseapp.com',
    databaseURL: 'https://easyway-cms-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'easyway-cms.appspot.com',
    measurementId: 'G-JLD3K3SC09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHQ8YRtmOzvDuTIZ6ZarzcUZWEM9Bsa-w',
    appId: '1:816152989290:android:d3f2e99e54b3746120c413',
    messagingSenderId: '816152989290',
    projectId: 'easyway-cms',
    databaseURL: 'https://easyway-cms-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'easyway-cms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkixBtnxC1AY3h5jUEoTNzra5vaDz-fMQ',
    appId: '1:816152989290:ios:3279a1afe09726a820c413',
    messagingSenderId: '816152989290',
    projectId: 'easyway-cms',
    databaseURL: 'https://easyway-cms-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'easyway-cms.appspot.com',
    iosBundleId: 'com.example.caseManagementTool',
  );
}
